export const plantList = [
    {
        name: 'monstera',
        category: 'classique',
        id: '1ed',
        isSpecialOffer: true,
        water: 1,
        light: null,
    },
    {
        name: 'ficus lyrata',
        category: 'classique',
        id: '2ab',
        isSpecialOffer: false,
        water: 1,
        light: 1,
    },
    {
        name: 'pothos argenté',
        category: 'classique',
        id: '3sd',
        isSpecialOffer: false,
        water: 1,
        light: 1,
    },
    {
        name: 'yucca',
        category: 'classique',
        id: '4kk',
        isSpecialOffer: false,
        water: 1,
        light: 1,
    },
    {
        name: 'olivier',
        category: 'extérieur',
        id: '5pl',
        isSpecialOffer: false,
        water: 1,
        light: 1,
    },
    {
        name: 'géranium',
        category: 'extérieur',
        id: '6uo',
        isSpecialOffer: false,
        water: 1,
        light: 1,
    },
    {
        name: 'basilique',
        category: 'extérieur',
        id: '7ie',
        isSpecialOffer: true,
        water: 1,
        light: 1,
    },
    {
        name: 'aloe',
        category: 'plante grasse',
        id: '8fp',
        isSpecialOffer: true,
        water: 1,
        light: 1,
    },
    {
        name: 'succulente',
        category: 'plante grasse',
        id: '9vn',
        isSpecialOffer: false,
        water: 1,
        light: 1,
    },
]
